# The title is the title of your Add-On
title: Alerts
# The description will be shown above the form when activating the Add-On
description: This Add-On can be used to set up a recurring alert that will email (and optionally Slack) you all matching Documents. It should generally include a filter for time to only include recently added documents, such as adding a query like `+created_at:[NOW-1HOUR TO *]`.
# Top level type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
# Properties are the fields for your form
properties:
  # the key is the name of the variable that will be returned to your code
    search:
    # the title is what will be shown as the form label
    title: Search Query (can include any text you use in a regular search):
    # a string is text
    type: string
  slack_webhook:
    # the title is what will be shown as the form label
    title: Slack Webhook
    # a string is text
    type: string
eventOptions:
  events:
    - hourly
